version: "3"
services:
  mezzio-project:
    container_name: mezzio-project
    hostname: mezzio-project
    image: mezzio-project
    volumes:
     - ".:/home"
    build: .
    restart: always
    command: /tmp/init.sh
    networks:
      app_net:
        ipv4_address: 10.20.20.20
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "10.20.20.0/24"
